version: 2.1
jobs:
  parameter_check:
    parameters:
      foo:
        type: string
        default: FOO_VALUE
    docker:
      - image: alpine
        environment:
          FOO: << parameters.foo >>
        command: ["sleep", "100"]
      - image: alpine
    steps:
      - run: "echo << parameters.foo >>"
      - run: "sleep 3"
workflows:
  version: 2
  sidecar_check:
    jobs:
      - parameter_check:
          name: check1
          foo: FOO_VALUE1
      # - parameter_check:
      #     name: check2
      #     foo: FOO_VALUE2
